# This workflow will install Python dependencies, build a website using Sphinx+Ablog and host it on GitHub pages

name: Sphinx-Ablog GitHub pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build website using ablog
      run: |
        ablog build -s kunstenaarsrol
